"""Generate discriminators for real historical bugs that have no surviving test.

Measured: across the largest historical pairs, **zero** existing repo tests discriminate the
before state from the after state. That is not a bug in the extractor -- these are
production files whose unit tests either need `playwright` or never covered the changed
logic. So the pairs are real but ungraded, and an ungraded pair cannot be a task.

The discriminator is therefore authored, from the real before/after themselves:

  * the ``after`` state is the reference: the assertions are generated by *executing it*,
    so they describe real behaviour rather than what the change looks like;
  * every generated assertion is then checked against the ``before`` state and kept only
    if it actually distinguishes them;
  * assertions that pass on both sides are discarded, because they test the untouched code;
  * an assertion that errors on ``before`` is only kept when it fails for the right reason --
    a value or behaviour difference, not an unrelated import or attribute error, which would
    make the task solvable by breaking the import.

The result is labelled ``differential`` everywhere, never ``repo_test``. It is a weaker
claim than an authentic regression test, and calling it anything else would launder an
authored oracle into a historical one.
"""
from __future__ import annotations

import ast
import json
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from bugbench.feedback import FeedbackChannel                  # noqa: E402
from bugbench.sandbox import build_sandbox, grader_env         # noqa: E402

#: Statement shapes a generated probe may call. Restricting the surface keeps probes
#: hermetic: anything that touches the filesystem, network, clock or randomness would make
#: the oracle unstable and the whole task unscoreable.
PROBE_SAFE_NODES = (
    ast.FunctionDef, ast.ClassDef, ast.Return, ast.Assign, ast.AugAssign,
    ast.Expr, ast.If, ast.For, ast.While, ast.List, ast.Dict, ast.Tuple,
    ast.Compare, ast.BoolOp, ast.BinOp, ast.UnaryOp, ast.Call, ast.Name,
    ast.Constant, ast.Attribute, ast.Subscript, ast.Slice, ast.IfExp,
)

BANNED = ("open", "eval", "exec", "compile", "__import__", "input", "exit",
          "quit", "breakpoint", "globals", "locals", "vars", "getattr", "setattr",
          "delattr", "memoryview", "print")


def probe_safe(tree: ast.AST) -> tuple[bool, str]:
    """Reject a function that could reach outside the sandbox or be unstable."""
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            if node.func.id in BANNED:
                return False, f"calls {node.func.id}()"
        if isinstance(node, ast.Import):
            return False, f"imports {', '.join(a.name for a in node.names)}"
        if isinstance(node, ast.ImportFrom):
            return False, "imports from another module"
        if isinstance(node, ast.Attribute) and node.attr in ("system", "popen", "environ",
                                                            "now", "random", "time"):
            return False, f"touches {node.attr}"
    return True, ""


def extract_callables(source: str, limit: int = 40) -> list[tuple[str, str]]:
    """Probe candidates, in descending order of how likely they are to be deterministic.

    Measured failure this replaces: requiring **zero-argument** callables found candidates
    in 1 of 28 real historical pairs, because production code is almost entirely functions
    that take arguments. So argument-taking callables are included, but ranked below
    parameterless ones, and only when their parameters have type annotations that can be
    filled from the module's own defaults and literals.

    What is still refused: anything that reads a clock, the network, the environment or
    randomness, and any function whose parameters cannot be given a literal value. A
    fabricated fixture would make the oracle a test of the fixture.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []
    out: list[tuple[str, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name.startswith("_") or node.name in BANNED:
            continue
        ok, _why = probe_safe(node)
        if not ok:
            continue
        seg = ast.get_source_segment(source, node)
        if not seg or len(seg) > 4000:
            continue
        params = node.args
        nargs = len(params.args) + len(params.posonlyargs) + len(params.kwonlyargs)
        if params.vararg or params.kwarg or nargs > 2:
            continue
        # Every parameter must have an annotation, so a literal can be supplied for it
        # rather than a guess.
        if any(a.annotation is None for a in params.args):
            continue
        rank = 0 if nargs == 0 else 1
        out.append((node.name, seg, rank))
        if len(out) >= limit:
            break
    out.sort(key=lambda t: (t[2], t[0]))
    return [(n, s) for n, s, _ in out]


def literal_args(source: str, fn_name: str) -> str | None:
    """Build the argument list for a probe from the module's own literals.

    Types are matched to plausible values so a `count: int` gets 1 and a `name: str` gets a
    short string. Returning None means no plausible call exists, and the probe is skipped.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return None
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == fn_name:
            # Defaults live on node.args.defaults, positionally aligned to the tail of
            # node.args.args -- an `arg` object has no `.default` attribute.
            positional = node.args.args
            defaults: list[str | None] = [None] * (len(positional) - len(node.args.defaults))
            defaults += [ast.unparse(d) for d in node.args.defaults]
            args: list[str] = []
            for a, default_src in zip(positional, defaults):
                ann = ast.unparse(a.annotation) if a.annotation else ""
                low = ann.lower()
                if default_src is not None:
                    args.append(default_src)
                elif "bool" in low:
                    args.append("True")
                elif "int" in low:
                    args.append("1")
                elif "float" in low:
                    args.append("1.0")
                elif "str" in low:
                    args.append('"x"')
                elif "list" in low:
                    args.append("[1, 2]")
                elif "dict" in low:
                    args.append('{"a": 1}')
                elif "bytes" in low:
                    args.append('b"x"')
                else:
                    return None
            return ", ".join(args)
    return None


def _probe_file(module_src: str, calls: list[tuple[str, str]], tag: str) -> str:
    """A pytest file that calls each function and records a stable fingerprint.

    ``calls`` is (name, args_source); an empty arg string means a parameterless call.
    """
    lines = [
        "import json, sys",
        "sys.path.insert(0, '.')",
        "",
        "PROBES = {}",
        "",
        "def _norm(v):",
        "    try:",
        "        return json.dumps(v, sort_keys=True, default=repr)",
        "    except Exception:",
        "        return 'UNSERIALISABLE'",
        "",
    ]
    for i, (fn, arglist) in enumerate(calls):
        lines += [
            f"def test_{tag}_{i}():",
            "    ns = {}",
            f"    exec(compile({module_src!r}, 'm.py', 'exec'), ns)",
            "    try:",
            f"        _r = ns[{fn!r}]({arglist})",
            "    except Exception as e:",
            "        PROBES[%r] = 'RAISED:' + type(e).__name__" % fn,
            "    else:",
            "        PROBES[%r] = _norm(_r)" % fn,
            "    print('PROBE%%s=%%s' %% (%r, PROBES[%r]))" % (fn, fn),
        ]
    return "\n".join(lines) + "\n"


@dataclass
class GeneratedOracle:
    """An authored discriminator for a real historical bug."""

    test_source: str
    probes: list[str] = field(default_factory=list)
    kept: list[str] = field(default_factory=list)
    rejected: list[str] = field(default_factory=list)
    kind: str = "differential"


def _run_probe(repo: Path, module_rel: str, module_src: str, probe_src: str,
               work: Path) -> dict[str, str]:
    d = build_sandbox(repo, work)
    (d / module_rel).parent.mkdir(parents=True, exist_ok=True)
    (d / module_rel).write_text(module_src)
    p = d / "test_generated_probe.py"
    p.write_text(probe_src)
    import subprocess
    r = subprocess.run([sys.executable, "-m", "pytest", "test_generated_probe.py",
                        "-q", "--tb=no", "-s"],
                       cwd=d, capture_output=True, text=True, timeout=240,
                       env=grader_env())
    out: dict[str, str] = {}
    for line in r.stdout.splitlines():
        if line.startswith("PROBE"):
            k, _, v = line[5:].partition("=")
            out[k.strip()] = v.strip()
    shutil.rmtree(work, ignore_errors=True)
    return out


def generate_oracle(repo: Path, module_rel: str, before_src: str, after_src: str,
                    work: Path, max_probes: int = 12) -> GeneratedOracle | None:
    """Build a probe file whose assertions hold on ``after`` and fail on ``before``.

    Returns None when no probe distinguishes the two states, which is the common case and
    the reason a pair without a surviving test is not automatically a task.
    """
    calls: list[tuple[str, str]] = []
    for name, _seg in extract_callables(after_src):
        arglist = literal_args(after_src, name)
        if arglist is not None:
            calls.append((name, arglist))
        if len(calls) >= max_probes:
            break
    if not calls:
        return None
    fns = [n for n, _ in calls]

    after = _run_probe(repo, module_rel, after_src, _probe_file(after_src, calls, "a"), work / "after")
    if not after:
        return None
    before = _run_probe(repo, module_rel, before_src, _probe_file(before_src, calls, "b"), work / "before")

    kept = [fn for fn in fns
            if fn in after and fn in before and after[fn] != before[fn]]
    if not kept:
        return None

    # A probe that merely raises on `before` is kept only when the *same* probe succeeds on
    # `after`; a difference where both raise is a crash, not a behaviour difference.
    kept = [fn for fn in kept
            if not after[fn].startswith("RAISED:")
            or after[fn] != before[fn]]

    test_src = _probe_file(after_src, [c for c in calls if c[0] in kept], "k")
    return GeneratedOracle(test_source=test_src, probes=fns, kept=kept,
                           rejected=[f for f in fns if f not in kept], kind="differential")
